pipeline:
  identifier: Build_harness_cie_lab_1712175688513
  name: Build harness-cie-lab
  orgIdentifier: default
  projectIdentifier: noahbootcampci
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.noahconn
        repoName: harness-cie-lab
  stages:
    - stage:
        identifier: build
        name: Build
        spec:
          caching:
            enabled: true
            paths: []
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: Build
                  spec:
                    connectorRef: account.noahdockerconn
                    image: nikpap/mvn-openjdk-8:harness
                    shell: Bash
                    command: |-
                      cd payment-service
                      mvn -Dmaven.test.skip=true clean install -X
                  timeout: ""
                  type: Run
              - step:
                  type: BuildAndPushDockerRegistry
                  name: pushtodockerhub
                  identifier: pushtodockerhub
                  spec:
                    connectorRef: account.noahdockerconn
                    repo: nikpap/mvn-openjdk-8:harness
                    tags: <+input>
                    dockerfile: /harness/payment-service/Dockerfile
                    optimize: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: ee
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        type: CI
        description: ""
